Rebase 3.32 (debian packaging)
endlessm/nautilus pull request #17
Opened 2019-03-22 17:19 UTC by uajain

https://phabricator.endlessm.com/T25164

2019-03-29 11:01 UTC, GeorgesStavracas requested changes

2019-03-29 11:01 UTC, GeorgesStavracas commented on debian/control.in
> +               eos-shell-content-dev,
Since you're on it, please move this package according to the alphabetical order.

2019-03-29 11:01 UTC, GeorgesStavracas commented on debian/rules
> -		-Denable-xmp=true \
Paranoid question: did you make sure we are not missing any of these flags?

2019-03-29 11:19 UTC, uajain commented on debian/rules
> -		-Denable-xmp=true \
Not sure I follow. Can you explain a bit more? 

(This is coming from upstream debian packaging and I only have a little idea of what it does, If you can give me the specifics, I can look into it.)

2019-03-29 11:51 UTC, GeorgesStavracas commented on debian/rules
> -		-Denable-xmp=true \
Did you double check that none of the flags that were dropped are needed by us?

2019-04-18 09:32 UTC, wjt commented
We have moved this package to OBS.

2019-04-18 09:32 UTC, closed without merging